### PR TITLE
Feature get user followings and followers

### PR DESCRIPTION
**Pull request by SimonHung8**
1. add getUserFollowings feature
2. passed get /users/:id/followings test
3. add getUserFollowers feature
4. passed get /users/:id/followers test

### CODE REVIEW

**Review by OneZerocococo — CHANGES_REQUESTED** [review]
1. Api should have "isFollowed" column
2. remove "account" column

**Comment by SimonHung8** [comment]
> 1. Api should have "isFollowed" column
> 2. remove "account" column

1. done
2. done
3. add getTopUsers feature

**Review by OneZerocococo — CHANGES_REQUESTED** [review]
Please change the variable name "followings" to "followers" in getUserFollowers

**Comment by SimonHung8** [comment]
> Please change the variable name "followings" to "followers" in getUserFollowers

renamed

**Review by OneZerocococo — APPROVED** [review]
ok

**Pull request merged**
